[package]
name = "routing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "routing"
crate-type = ["cdylib"]

[dependencies]
ordered-float = "4.2.0"
petgraph = "0.6.4"
pyo3 = "0.19.0"
